version: "3"
services:
  api:
    container_name: "reservation-service"
    build: .
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - 3002:3002
      - 9238:9228
    command: bash -c "sleep 10  && npm start"
    depends_on:
      - mongoreserve
   

  mongoreserve:
    container_name: mongodb_reservation
    image: mongo
    restart: always
    command: mongod --port 27019
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: user
      #MONGO_INITDB_ROOT_PASSWORD: 12
    ports:
       - 27019:27019


networks:
  ovl_net:
    external:
      name: airline_service

  