version: "3"
services:
  api:
    container_name: "flight-registration-service"
    build: .
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - 3001:3001
      - 9228:9228
    command: bash -c "sleep 8  && npm start"
    depends_on:
      - mongoflight

  mongoflight:
    container_name: mongodbflight
    image: mongo
    restart: always
    command: mongod --port 27018
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: user
      #MONGO_INITDB_ROOT_PASSWORD: 12
    ports:
       - 27018:27018

networks:
  ovl_net:
    external:
      name: airline_service

  