version: "3"
services:
  api:
    container_name: "user-registration-service"
    build: .
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - 3000:3000
    command: bash -c "sleep 10  && npm start"
    depends_on:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: user
      #MONGO_INITDB_ROOT_PASSWORD: 12
    ports:
       - 27017:27017

networks:
  ovl_net:
    external:
      name: airline_service

  